### ISSUE TITLE
Autocomplete search box for Google provider

### ISSUE THREAD

**Issue by alexgleith** [smeijer/leaflet-geosearch#10]
Is it possible to implement Google's Autocomplete functionality for this search provider?

Please let me know if someone's done it, as I want to implement it but feel that someone else will do a better job...

https://developers.google.com/places/documentation/autocomplete

**Comment by smeijer** [comment]
It looks like #29 fixes this. Should be awesome if someone is willing to rebase that PR on top of the latest version.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```
