### ISSUE TITLE
Closing Results with Autocomplete and Bar Style

### ISSUE THREAD

**Issue by Schumi09** [smeijer/leaflet-geosearch#103]
Hi there,

I intended to use this lovely plugin with the OSM-Provider and autocomplete. While I can get results and choose on of them, the result list does not close on enter/click. 

I could not find anything related here, but what I have described should be the default behaviour I would expect as user. By default the only way to close it was to clear the input, e.g. with ESC key.

Is there anything I missed or is there some workaround?

Best regards,
Daniel

**Comment by enocholumide** [comment]
Hi, could you help me; I cannot seem to figure out how I can get the plugin innto my Angular2 project, it kee saying cannot find module during compilation thank you
![image](https://cloud.githubusercontent.com/assets/24214602/24579947/cead508e-16ff-11e7-8c6a-ab83561b7e91.png)

**Comment by cajus** [comment]
@Schumi09: I was just looking for that feature, too. Either I don't see it in the source, or its not possible. Worked it around using something like that:

```
      map.on("geosearch/showlocation", function() {
        var ev = new Event("fake");
        searchControl.clearResults(ev);
        searchControl.onClick(ev);
      });
```

Where *map* is the map instance and *searchControl* is the geo search instance. Not that nice, but it seems to work.

**Comment by smeijer** [comment]
@cajus is right. This feature is currently not existing. A PR for this would be most welcome.

**Comment by cajus** [comment]
@smeijer I can add a PR, but as I've a completely different workflow, I'm not sure how to build the directly includeable geosearch.js bundle.

`./node_modules/.bin/webpack --config webpack.config.babel.js`

generates a broken bundle. What's the correct way?
