### ISSUE TITLE
Cannot find module leaflet-geosearch! :(

### ISSUE THREAD

**Issue by enocholumide** [smeijer/leaflet-geosearch#104]
I installed via npm, but my map reload was prevented saying can not find module.. dont know what is wrong: please help

![image](https://cloud.githubusercontent.com/assets/24214602/24579927/61f10206-16ff-11e7-8210-7a87cdd74ec9.png)

**Comment by smeijer** [comment]
You can fix your problem by not including from the `lib` folder, but using a default `import` instead.

```js
import { GeoSearchControl, OpenStreetMapProvider } from 'leaflet-geosearch';

const provider = new OpenStreetMapProvider();

const searchControl = new GeoSearchControl({
  provider: provider,
});

const map = new L.Map('map');
map.addControl(searchControl);
```

Please check the readme and the provided snippets in the demo: http://smeijer.github.io/leaflet-geosearch
