### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by tonitoelgalo** [smeijer/leaflet-geosearch#106]
Hi everybody 

Autocomplete does not work for me .  everything normal ?

**Comment by smeijer** [comment]
Do you have a sample online? What provider are you using?

**Comment by tonitoelgalo** [comment]
Ouuups , so sorry , it's working great with Mapbox and Photon

**Comment by smeijer** [comment]
Mapbox and photon? Can you explain a bit more? 

Are you using this control? And what provider are you using that was causing the no-autocomplete bug?
