### ISSUE TITLE
Demo pages are broken in IE11

### ISSUE THREAD

**Issue by hanginwithdaddo** [smeijer/leaflet-geosearch#108]
Does the latest version of this plugin work with IE 11? I see errors trying to access even the demo page:
http://smeijer.github.io/leaflet-geosearch/#search

Here is the error that I am seeing in bundle.js:

SCRIPT438: Object doesn't support property or method 'find'
File: bundle.js, Line: 2204, Column: 8
	      var page = pages.find(function (p) {
	        return p.slug === (hash || 'search');
	      });

![image](https://cloud.githubusercontent.com/assets/14109413/24812944/190e423e-1b9a-11e7-8f13-16d47ad0f3e1.png)

**Comment by smeijer** [comment]
I haven't tested yet, but the find is something from the docs their selfs. We should indeed make sure the control and providers do support IE11.

**Comment by ville6000** [comment]
IE11 needs polyfills for Array.prototype.includes and Promise.

**Comment by smeijer** [comment]
Fixed. Although the `onfocus` and `onblur` events of the geosearch control seem to behave a little strange. 😕
