### ISSUE TITLE
Question: How to use the latest version of this plugin on browsers that do not support the "import" statement?

### ISSUE THREAD

**Issue by hanginwithdaddo** [smeijer/leaflet-geosearch#109]
I am feeling really stupid at the moment. An earlier version of this plugin did not require the use of "import" statements and one could reference the GeoSearch control using L.Control.GeoSearch. How do I use the latest version of this plugin, given that most browsers do not support the "import" javascript keyword yet, and without using a transpiler such as Babel?
Sorry for being so ignorant.

**Comment by hanginwithdaddo** [comment]
It also appears by looking at bundle.js that the footprint of this plugin now includes all of the Leaflet source. Is this true?

I pulled the latest using npm.

**Comment by smeijer** [comment]
If you don't want to use npm and/or an bundler, you can still use the bundle trough `unpkg`. 

Regarding the last question, the bundle does include the leaflet geosearch control, but not the entire leaflet source.  The bundle is only 29kb and includes all providers. If you wish to include only the required parts, you should get comfortable by using npm and some bundler like babel / webpack. But that depends more on how you are building your front-end application. 

Please see the comment on the following issue on how to use this library without npm: https://github.com/smeijer/leaflet-geosearch/issues/92#issuecomment-276009606 . I cannot recomend it, but to minify the bundle even more; you can also add only the required parts (like your control, and a single provider) directly from `unpkg` trough https://unpkg.com/leaflet-geosearch@latest/lib/

But I would strongly recommend pointing to the latest bundle like the example in the linked comment. This to avoid any difficulties in migration paths when releasing new versions.

**Comment by hanginwithdaddo** [comment]
Thank for your feedback. The window.GeoSearch.GeoSearchControl reference is the part I was missing. I will give this a try later today.
Dave
