### ISSUE TITLE
Safari autocomplete fails

### ISSUE THREAD

**Issue by michaelhobbs** [smeijer/leaflet-geosearch#110]
Autocomplete does nothing in Safari. Non error. When triggering a search in console there is the folowing error:

`ReferenceError: "Can't find variable: fetch"`
http://stackoverflow.com/questions/35830202/fetch-not-defined-in-safari-referenceerror-cant-find-variable-fetch

Can you add a polyfill like in the stackoverflow link?

**Comment by smeijer** [comment]
Do you mean in the demo? Or the library itself?

**Comment by michaelhobbs** [comment]
Both.
I "fixed" this by added this [polyfill fetch library](https://github.com/github/fetch) to my project.
I think it would make sense to add it as a dependency to leaflet-geosearch?

**Comment by smeijer** [comment]
I decided not to include this polyfill, as there are also users that don't want to support the older browsers in favor of saving a couple of bytes. The polyfill can added by the end user, like you did.

We should however mention this in the docs. Thanks for reporting.
