### ISSUE TITLE
Missing CSS on control when using code snippets from README

### ISSUE THREAD

**Issue by jlengrand** [smeijer/leaflet-geosearch#113]
Hi there, 

It is not the first issue I am creating today, so it might well be that the issue come from me :).

I am trying to embed leaflet-geosearch inside a leaflet map. 

For this, I have used pretty much the same template as indicated on the README : 

```
import { GeoSearchControl, OpenStreetMapProvider } from 'leaflet-geosearch';

const provider = new OpenStreetMapProvider();

const searchControl = new GeoSearchControl({
  provider: provider,
});

const map = new L.Map('map');
map.addControl(searchControl);
```

The only difference for me is that Leaflet is defined already at global level, so I don't import it. 

I have installed leaflet-geosearch as such : 

```
npm install --save leaflet-geosearch
```

I am using the latest ("^2.0.3").

When doing this, the functionality works as expected, but it is pretty much missing the css. 

![2017-04-15_16h42_59](https://cloud.githubusercontent.com/assets/921666/25070903/534ae4c2-22aa-11e7-8251-4dee9ccfc6aa.png)

After fiddling around for a while, I realized that I could get around the issue by importing the css files from the node_module directly : 

```
import 'leaflet-geosearch/dist/style.css'
import 'leaflet-geosearch/assets/css/leaflet.css'
```

When adding those two lines, I get exactly the same result as the demo website. 

Is this expected behaviour? 
Thanks, 
Julien

**Comment by smeijer** [comment]
Yes, this is expected. The control doesn't have styles if you don't import them.

Otherwise you wouldn't be able to easily override styles. And this is the best compatibility with leaflet.
