### ISSUE TITLE
local nominatim search

### ISSUE THREAD

**Issue by t3asp00n** [smeijer/leaflet-geosearch#119]
I've been playing around with offline maps and in order to do geocoding I installed a local Nominatim server, but I'm having trouble finding a way to change the url on geosearch so it points to my local Nominatim search. I've changed the url found on OpenStreetMap provider, bundle.js and bundle.min.js and no luck. Any help would be much appreciated.

**Comment by smeijer** [comment]
It's currently not possible to change the domain part of the openstreetmap provider. So what you can do is write your own provider by copying 99% of the one provided to you. A PR to make the domain part configurable would also be welcome.

This is the file you want to copy: https://github.com/smeijer/leaflet-geosearch/blob/develop/src/providers/openStreetMapProvider.js

**Comment by smeijer** [comment]
I'm closing this one for now. Please let me know if you need any help.
