### ISSUE TITLE
dist/style.css cannot be used with dist/bundle.js

### ISSUE THREAD

**Issue by simon04** [smeijer/leaflet-geosearch#126]
Due to the identifiers such as `.leaflet__leaflet-control-geosearch___35AKI` (originating from `css-loader`'s config `localIdentName` in `webpack.config.babel.js`), the [distributed CSS file](https://unpkg.com/leaflet-geosearch@2.4.0/dist/style.css) cannot be used with the [`bundle.js`](https://unpkg.com/leaflet-geosearch@2.4.0/dist/bundle.js).

The `docs/index.html` contains both the `dist/style.css` as well as the `assets/css/leaflet.css`: https://github.com/smeijer/leaflet-geosearch/blob/4a443db/docs/index.html#L16-L17

**Comment by skipjack** [comment]
Ran into the same issue, i.e. the following is needed:

``` js
import 'leaflet-geosearch/dist/style.css'
import 'leaflet-geosearch/assets/css/leaflet.css'
```

This isn't super clear as the `README` doesn't really mention much about styling (besides the `style` option). Any particular reason for separating the two stylesheets?

**Comment by smeijer** [comment]
To be honest, I think the dist file is just not compiled like it should. PR to fix it would be most welcome.

**Comment by smeijer** [comment]
`leaflet-geosearch v3` fixes this issue. 

Either add `https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.css` to your head, or import from `leaflet-geosearch/dist/geosearch.css`

Sorry for the long wait.
