### ISSUE TITLE
Keeping markers

### ISSUE THREAD

**Issue by maettyhawk** [smeijer/leaflet-geosearch#127]
Since I'm working on an application including a map which has to go well with mobile devices, I'm looking for a way to keep markers until another location has been selected in the search menu. In cases where maps are very small (f.e. 320x320px), the results hide the whole map unterneath, so it might be useful to keep them visible.

Alternatively, hiding the results when the search input looses focus, might do the trick as well. I've already tried to hide/show (using CSS) the result menue depending on the class _active_, but on this way the whole menue disappears before the selected item triggers a change of location.

Thanks for your help in advance

maettyhawk

**Comment by Greg-Gravyty** [comment]
Have you checked out the autoClose option on the GeoSearchControl? It closes the dropdown when an item is selected. https://github.com/smeijer/leaflet-geosearch/blob/develop/readme.md#geosearchcontrol

**Comment by maettyhawk** [comment]
Hi there, I checked out the autoClose option, and, yes, it closes the dropdown, but it also makes the marker(s) disappear and (even worse) resets the search field.

**Comment by Greg-Gravyty** [comment]
Oh I see. Yeah, it seems like you'd need to do something custom for that.

**Comment by smeijer** [comment]
#128 closed this one a while back. Thanks for the contributions 😄
