### ISSUE TITLE
Triggers map.click

### ISSUE THREAD

**Issue by simon04** [smeijer/leaflet-geosearch#129]
Clicking the search button or the search input field triggers the [map.click event](http://leafletjs.com/reference-1.0.3.html#map-event).

To reproduce (search button):
1. Open https://smeijer.github.io/leaflet-geosearch/#google
2. Open developer console (F12), invoke `map.on('click', () => alert(1))`
3. Click the search icon
4. Alert dialog pops up!

To reproduce (search input fiield):
1. Open https://smeijer.github.io/leaflet-geosearch/#openstreetmap
2. Open developer console (F12), invoke `map.on('click', () => alert(1))`
3. Click the search input field ("Enter address")
4. Alert dialog pops up!

**Comment by smeijer** [comment]
Thanks for the report. This will be fixed as soon as #138 is merged.

**Comment by smeijer** [comment]
And that will be now.

**Comment by simon04** [comment]
As far as I can tell, the issue is not fixed. Both ways to reproduce still display the alert dialog.

**Comment by arminus** [comment]
Still not working (unless I miss something here): https://jsbin.com/menogenequ/edit?html,console,output

**Comment by dgana** [comment]
Any quick solution?
