### ISSUE TITLE
Country and bounds are not honoured 

### ISSUE THREAD

**Issue by ewe1991** [smeijer/leaflet-geosearch#132]
Hi, 

I can not get the GoogleProvider to limit the GEO Search results to only UK. I have set the country and the bounds however no difference.
 
I have a simple example [here](https://codepen.io/wearebold/pen/VWWrQK) 

Many Thanks, 
Elliott

**Comment by ewe1991** [comment]
found the fix:
components:'country:GB',

**Comment by smeijer** [comment]
Awesome, thanks for letting know you've solved it.
