### ISSUE TITLE
Add vendor prefixes to CSS rules

### ISSUE THREAD

**Issue by QimatLuo** [smeijer/leaflet-geosearch#133]
Thanks you provide this plugin, and I'm using this plugin on Ionic and deployed to iOS.
But the some of phone is not updated to latest version, for example iOS 8.
That cause some UI looks strange, like the search icon.
Maybe you can add autoprefixer in webpack and config to support iOS 8. That can fix most of old browser issue.

**Comment by smeijer** [comment]
I'll take a look at this. But I must warn that I cannot test it on iOS, as i don't own any Apple devices.
