### ISSUE TITLE
Typings for typescript support please

### ISSUE THREAD

**Issue by diegohb** [smeijer/leaflet-geosearch#135]

**Comment by fehro** [comment]
dito

**Comment by smeijer** [comment]
PR would be most welcome

**Comment by carlosedof** [comment]
no answers yet? dawm

**Comment by dimabory** [comment]
@smeijer 
https://www.npmjs.com/package/@types/leaflet-geosearch

**Comment by dimabory** [comment]
@smeijer What do you think about mentioning this in _README_?

**Comment by smeijer** [comment]
I think that would be great. Can you submit a PR?

**Comment by dimabory** [comment]
> I think that would be great. Can you submit a PR?

Sure, I will do that as soon as I have time a bit more.
