### ISSUE TITLE
Search fails for some queries with Nominatim

### ISSUE THREAD

**Issue by francislavoie** [smeijer/leaflet-geosearch#144]
Example: I first type "rogers centre" in the search, and I get these results:

http://nominatim.openstreetmap.org/search?format=json&q=rogers%20centre

Then I click on the first result, which does a search for this:

http://nominatim.openstreetmap.org/search?format=json&q=Rogers%20Centre,%201,%20Blue%20Jays%20Way,%20CityPlace,%20Old%20Toronto,%20Toronto,%20Ontario,%20M5V%201J4,%20Canada

Which returns no results. I can also replicate with many other places. Maybe the API should be querying the `place_id` of the result instead of the `display_name`? Would probably be more accurate.

**Comment by francislavoie** [comment]
I think I have an idea for a fix.

If for the drill-down (click on a result) request we instead do a reverse geocode using the `osm_id` and `osm_type`, it should work.

Example for "rogers centre" like above

http://nominatim.openstreetmap.org/reverse?format=json&osm_type=W&osm_id=7969701

**Comment by smeijer** [comment]
Sounds awesome. Can you submit a PR?

**Comment by francislavoie** [comment]
My JS skills are still pretty weak unfortunately, not sure how to implement this. It seems like this would be a pretty significant change, since currently everything relies on the `label` string, but we need to use other non-displayed data for the search query. Doesn't seem like this would work with other providers either unless they also have the same style of reverse queries.

**Comment by francislavoie** [comment]
Hmm, some ideas:

https://github.com/smeijer/leaflet-geosearch/blob/develop/src/leafletControl.js#L86

This line could be replaced with something like `queryWithResult` which takes in a result object instead of a query string, then the provider could use whatever data from the result object to build it's subsequent query (e.g. for OSM, the `osm_id` and `osm_type`).

**Comment by francislavoie** [comment]
Just some pseudocode (cause I don't really know what I'm doing) for the base provider in `provider.js`:

```js
  async search({ query, queryWithResult }) {
    // eslint-disable-next-line no-bitwise
    const protocol = ~location.protocol.indexOf('http') ? location.protocol : 'https:';
    if (queryWithResult) {
      const url = this.endpointWithResult({ queryWithResult, protocol });
    } else {
      const url = this.endpoint({ query, protocol });
    }

    const request = await fetch(url);
    const json = await request.json();
    return this.parse({ data: json });
  }
```

And then in `openStreetMapProvider.js`, something like:

```js
  endpointWithResult({ queryWithResult, protocol } = {}) {
    const { params } = this.options;

    const paramString = this.getParamString({
      ...params,
      format: 'json',
      osm_id: queryWithResult.osm_id,
      osm_type: this.translateOsmType(queryWithResult.osm_type),
    });

    return `${protocol}//nominatim.openstreetmap.org/reverse?${paramString}`;
  }

  translateOsmType(osm_type) {
    if (osm_type === "node") {
      return "N";
    }
    if (osm_type === "way") {
      return "W";
    }
    if (osm_type === "relation") {
      return "R";
    }
    return ""; // Unknown
  }
```

**Comment by smeijer** [comment]
Thanks for the research. Sounds like also passing trough the `result` can help in fixing this.

Something like `async search({ query, data })` (where data is the `result`). I guess the `openstreetmap provider` can implement the `search` method himself, instead of using the default one.

This shouldn't be fixed in `provider.js`, it should be fixed in the search control (passing trough more data), and by custom methods (the `search`) in the openstreetmap provider. Like the bing provider does to fix the json-p issue.

**Comment by francislavoie** [comment]
It seems LocationIQ is the same as OSM in terms of API, so that provider should be updated at the same time. See https://unwiredlabs.com/geocoding-api#reverse

**Comment by francislavoie** [comment]
Re your point about the specific providers implementing `search`, I don't think that would work without changing `provider.js`, because technically you'd be changing the function signature and usage of the function. The base implementation would still need to handle being passed `data` for it to be correct.

Interesting note: I found that just hitting `ENTER` when using `autoClose: true` and `keepResult: true` does work when there are place names involved because it seems to be just using the first result from the list in that case... but picking a result from the list when autocompleted stills fails as-is. I'm implementing a geofence picker (find a point, then pick a radius for that point), and I'll have to hold off on pushing my implementation for now because of this bug.

Let me know if there's anything else you need from me to get this fixed

**Comment by smeijer** [comment]
You're welcome to submit a PR. I can take a look at it when you're done, and give my feedback, to have it merged asap.

Please be sure to keep backwards compatibility. Add extra arguments, but don't remove / rename existing.

**Comment by francislavoie** [comment]
PR is ready for review :smile:
