### ISSUE TITLE
map.on(click)

### ISSUE THREAD

**Issue by netforce** [smeijer/leaflet-geosearch#148]
Following #92, and reading #138 and #129 i got myself a working version with draggable markers, updating location variables and almost completely as i want, but..

I'd still like to have the ability to add a marker onto the same map without using the searchplugin..
When i implement map.on('click') the bug of a marker being placed when clicking inside the searchbar re-appears.

I guess the map.on('click') even bypasses the disableHandlers and restoreHandlers wich fixed #138 ?
As i'v got this far in getting this to work i'd be ashamed for not getting this to work.

For my code see https://codepen.io/netforcenl/pen/xXQMrb or https://jsfiddle.net/netforcenl/0a4b3ufg/11/
Now i'm creating the jsfiddle from my original code i'm noticing that when i click the "close search results" x, i also lose my result (marker), and the searchbar does not close when selecting one result..

I'm seriously overlooking something it seems and any help is appreciated.

unpkg leaflet@1.2.0
unpkg leaflet-geosearch@2.6.0

**Comment by hartman** [comment]
I have this problem too. Quite annoying. Anyone figured out a solution ?

**Comment by dgana** [comment]
Any quick solution for this issue?

**Comment by AceCat** [comment]
Wanted to check in and see if anyone had found a solution for this issue, it's driving me crazy.

**Comment by ppulwey** [comment]
This is still the case. Any update on this?

**Comment by smeijer** [comment]
Is there an updated reproduction available?

**Comment by smeijer** [comment]
I'm unable to reproduce this. Please let me know if you're able to create a reproduction based on this pen, so we can reopen and fix if I'm missing something.

https://codepen.io/smeijer/pen/YzGveWN?editors=0010

**Comment by ppulwey** [comment]
I'm using Vue2Leaflet with this wrapper for your package: https://www.npmjs.com/package/vue2-leaflet-geosearch
The npm version is outdated. I've installed latest version from Git-Repo.
It's working fine now! Thanks for your effort! 👍
