### ISSUE TITLE
Search Control style

### ISSUE THREAD

**Issue by p59crw** [smeijer/leaflet-geosearch#151]
![screenshot from 2017-11-28 13-37-01](https://user-images.githubusercontent.com/5456555/33333648-f40471fa-d441-11e7-8dc0-2357bc1a1bd7.png)

Instead of appearing normally like a centered searchbar, the search control (set to default based on example code for OSM provider), appears like the image above.

I made sure that the leaflet-geosearch was installed via NPM and that all files were found in the node module folder.

I'm using: 
Leaflet v. 1.2.0
Node v. 8.4.0
Angular CLI v. 1.5.2

Could my versions be an issue? I tried changing some CSS but nothing fixed the appearance of the search.

**Comment by smeijer** [comment]
Do you have it online somewhere? It looks like a css file is missing.

**Comment by p59crw** [comment]
No, I don't have it online, but I just checked that it the package was installed correctly by reinstalling. It was installed correctly, but nothing changed.

I copied and pasted the code under "Using with LeafletJS" with no other modifications.

**Comment by smeijer** [comment]
yeah, sorry. You also need to include a stylesheet. 

https://unpkg.com/leaflet-geosearch@2.6.0/assets/css/leaflet.css

**Comment by p59crw** [comment]
Thanks. That was the problem. Works perfectly now.

**Comment by Juanryhn** [comment]
Can I custom the style wit css preprocessor like sass ?
