### ISSUE TITLE
Search results are slightly hidden under other controls

### ISSUE THREAD

**Issue by newmanw** [smeijer/leaflet-geosearch#155]
The search results 'pane' overlaps other controls.
I suppose the z-index could be changed but then that would hide the controls.

<img width="668" alt="screen shot 2018-01-16 at 8 32 41 pm" src="https://user-images.githubusercontent.com/3382274/35024390-700684f6-fafc-11e7-99f4-fe6f03ccf8bc.png">

Wondering if you have given thought to moving the results 'pane' such that there is no overlap with other controls.

**Comment by smeijer** [comment]
Fixed in v3.0.0

![image](https://user-images.githubusercontent.com/1196524/82730646-8596c480-9d01-11ea-9e8e-7a6f67514f6c.png)
