### ISSUE TITLE
Search bar and results rendering behind map tile

### ISSUE THREAD

**Issue by dirodriguezm** [smeijer/leaflet-geosearch#160]
Hi 

I'm having trouble with the GeoSearchControl style.
If I leave it default or "button" it looks like this:
![imagen](https://user-images.githubusercontent.com/18015991/39680979-e3e1e5b0-517c-11e8-91ba-2d783d23fdb6.png)

If I set it to "bar" it renders but behind the map tile.
![imagen](https://user-images.githubusercontent.com/18015991/39681032-5d129b5a-517d-11e8-93cc-01dbb4e426c4.png) 
![imagen](https://user-images.githubusercontent.com/18015991/39681045-7fd4c082-517d-11e8-9dfc-d3d1efdad38c.png)

I am using react with react-leaflet. This is my  MapControl class:
```
export default class SearchBar extends MapControl{
  constructor(props){
    super(props);
  }

  createLeafletElement() {
    return GeoSearchControl({
      provider: new OpenStreetMapProvider(),
      style:'bar',
      autoComplete: true,
      autoClose:true,
    });
  }
}
```

And the <Map> component using it like this:
```
<Map
  center={position}
  zoom={this.state.zoom}
  style={style}
  onClick={this.mapClicked}
  onLocationFound={this.handleLocationFound}
  ref="map"
  >
  <TileLayer
    attribution="&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  />
  {this.state.markers.map((position) =>
    <Marker position={position}>
      <Popup>
        <span>
          A pretty CSS3 popup. <br /> Easily customizable.
        </span>
      </Popup>
    </Marker>
   )}
  <SearchBar/>
</Map>
```

Any help would be appreciated

**Comment by smeijer** [comment]
Looks like you're missing the style sheet. Did you include it?

**Comment by dirodriguezm** [comment]
@smeijer I installed it with npm and the leaflet.css file is located in `node_modules/leaflet-geosearch/assets/css/`

Do I need to include it in some way ?

**Comment by TitanFighter** [comment]
> whenever I click on it, a map onClick function is called so I can't add markers onClick. Is there a workaround for this

```
autoClose: true,
keepResult: true  
```

`autoClose` closes the result list if a result is selected by click/enter.
`keepResult` is used to keep the selected result in the search field. This prevents markers to disappear while using the autoClose feature.
