### ISSUE TITLE
Trouble installing geosearch

### ISSUE THREAD

**Issue by chimrichalds72** [smeijer/leaflet-geosearch#163]
I've tried installing with npm... not sure what that did.   Is there a basic step by step guide to manually download and arrange folders and how to reference them in the script?

**Comment by smeijer** [comment]
I'm closing this one, as the docs have definitely been improved upon, and will be further improved in #215.

**Comment by smeijer** [comment]
Together with `leaflet-geosearch v3`, the new docs have been deployed to https://smeijer.github.io/leaflet-geosearch. I hope that helps.

Please let me know if something is still not clear.
