### ISSUE TITLE
LocationIQProvider is not exported

### ISSUE THREAD

**Issue by wheercool** [smeijer/leaflet-geosearch#165]
Steps to reproduce: 
(from docs)
```javascript
import { LocationIQProvider } from 'leaflet-geosearch';

const provider = new LocationIQProvider({ 
  params: {
    key: '__YOUR_LOCATIONIQ_KEY__',
  },
});
```

but LocationIQProvider is not defined

**Comment by Heni-ghodbane** [comment]
@smeijer 
I am interested to add more providers to this module.
can you please describe the steps of the required changes we need to fix this issue and how we could add new providers (@types and leaflet-geosearch).
I have tried but I failed!

**Comment by smeijer** [comment]
@Heni-ghodbanewhat did you try exactly, and what failed?

I see that `LocationIQProvider` is indeed not being [re-exported](https://github.com/smeijer/leaflet-geosearch/blob/develop/src/index.js), but it should still be possible to import it directly from `'leaflet-geosearch/lib/providers/locationIQProvider.js'`, maybe that's something that this library should stimulate anyway, to reduce the bundle size.

At this moment, all (apparently minus LocationIQ) providers are included in the bundle. Which doesn't make sense when you only want to use one.

**Comment by Heni-ghodbane** [comment]
I have downloaded the project and the @types in order to fix that import problem, and as a next step I wanted to implement 2 other providers but I was little bit confused.

I have just imported like you mentioned above but it doesn't work and returns an error: 

> ERROR Error: Uncaught (in promise): TypeError: leaflet_geosearch_lib_providers_locationIQProvider_js__WEBPACK_IMPORTED_MODULE_6__.LocationIQProvider is not a constructor

**Comment by smeijer** [comment]
The bug has been fixed in `vNext`, and will be released soon(ish).

@Heni-ghodbane , you've mentioned that you wanted to add more providers to the library. Which providers where you considering when you wrote that?

I can focus on writing instructions in the scope of #215 if your still interested.

**Comment by Heni-ghodbane** [comment]
@smeijer thanks for your comment, this 2 APIs mapquestapi openrouteservice

**Comment by smeijer** [comment]
Closing this issue as the ongoing discussion is out of context. @Heni-ghodbane, Can we continue the docs/provider discussion [here](https://github.com/smeijer/leaflet-geosearch/pull/215#issuecomment-614125732)? (As written there, I've updated the docs :slightly_smiling_face:  )

**Comment by smeijer** [comment]
The export of the provider has been fixed in `leaflet-geosearch v3`, which has been released :tada:
