### ISSUE TITLE
Search Country specific for Esri and Bing Providers 

### ISSUE THREAD

**Issue by anujkamat29** [smeijer/leaflet-geosearch#168]
I am able to get search results country specific for Open Street Maps and Google. Not the same for Esri and Bing.

For Open Street Maps I have used **countrycodes: '_Country_code_'**

For Google I have used **components:'country:_Country_code_',**

Please help in the remaining two providers

**Comment by smeijer** [comment]
You should check the documentation of the api's. It will be possible to provide the setting to your provider, as long as the API supports it. The provider will just forward it to the API. He doesn't do anything with the settings himself.

Links to the API documentation of the default providers are all placed in the README.md. Please see there. Not all API's do provide this option.

**Comment by ertejaspatel** [comment]
Hi Smeijer, 

Thanks for this awesome library...

Does this library pass any additional parameter to the search provider?

i.e.
searchProvider.search({ query: input, components: "country:ca|country:au" })

Thanks,

**Comment by smeijer** [comment]
Yes it does. The arguments that you're providing to the `provider` are passed trough.

They should be given trough the constructed though. Not when calling the `search` method.
