### ISSUE TITLE
Attach GeoSearch to a static DOM element

### ISSUE THREAD

**Issue by wboykinm** [smeijer/leaflet-geosearch#17]
First: THANKS FOR THE AWESOMENESS!!! This is the easiest and most-comprehensive geocoding library I've seen in three years. 

Second: Perhaps it's a bit TOO easy. I'm trying to build an app that buckles bootstrap onto leaflet 5.1 (cartodb.js, actually), and I want to use a static bootstrap `<input>` tag as the GeoSearch element. This is so I can attach the typeahead function and position the search dialog within the bootstrap-heavy layout. I saw that [Sajjad sort of adapted the position thing already](https://github.com/smeijer/L.GeoSearch/pull/2), but it doesn't seem to allow for positioning like a static element.

[This section of the code](https://github.com/smeijer/L.GeoSearch/blob/master/src/js/l.control.geosearch.js#L42-56) where the search box is created programmatically is what's killing me. And my question is this: 

If I comment out the above lines, what do I need to do beyond attaching `id="leaflet-control-geosearch-qry"` to the search input form element? At the moment that doesn't work on its own, and commenting them out just breaks the map with an `uncaught typeError`.

[Demo here](http://dev.geosprocket.com/geosearch/intel/)

Thanks again!

**Comment by smeijer** [comment]
Old topic; so closing. Leaving some info for people that come here trough searching.

---

From version 2 this can easily be done by simply not binding it to Leaflet itself.

Base principle:
```js
// import
import { OpenStreetMapProvider } from 'leaflet-geosearch';

// setup
const provider = new OpenStreetMapProvider();

// search
const results = await provider.search({ query: input.value });
```

Attaching to an existing form:

```js
import { OpenStreetMapProvider } from 'leaflet-geosearch';

const form = document.querySelector('form');
const input = form.querySelector('input[type="text"]');

form.addEventListener('submit', async (event) => {
  event.preventDefault();

  const results = await provider.search({ query: input.value });
  console.log(results); // » [{}, {}, {}, ...]
});
```

Also see: https://github.com/smeijer/leaflet-geosearch#usage
