### ISSUE TITLE
undefined is not an object (evaluating 'this.results[e]')

### ISSUE THREAD

**Issue by jb2b38** [smeijer/leaflet-geosearch#181]
I run into this error quite often.
It happens every time I type my search, and hit the return key BEFORE the provider could return me a search result. Doing so will always result in a JS error.

That's when I get this error in bundle.min.js:1213.

On the other hand, if the search provider was able to return a suggestion before hitting the return key, the problem will not appear at all, even if the next time I type was fast enough : it has to happen on the first search (or any consecutive searches being fast enough).

For now I reduced the autoCompleteDelay to a smaller value of 150, but this is not ideal is it doesn't cover the case of a copy-paste enter for example.

**Comment by deadbeef404** [comment]
I've run into this bug, with the following error in Chrome:
`Uncaught TypeError: Cannot read property '-1' of undefined`

I've made a PR for this, above.

**Comment by smeijer** [comment]
Fixed by #200
