### ISSUE TITLE
GeoSearchControl not exported in @types/leaflet-geosearch

### ISSUE THREAD

**Issue by piotrlarys** [smeijer/leaflet-geosearch#199]
In angular 8+ cannot import GeoSearchControl because it is not exported in @types/leaflet-geosearch

**Comment by dimabory** [comment]
@piotrlarys currently, `@types/leaflet-geosearch` provides types only for providers.

**Comment by dimabory** [comment]
@piotrlarys new version of `@types/leaflet-geosearch` has been published.
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37894#issuecomment-524899347
