### ISSUE TITLE
Missing search with parameters in Openstreepmap provider

### ISSUE THREAD

**Issue by giacomotontini** [smeijer/leaflet-geosearch#206]
As stated in [Nominatim](https://nominatim.org/release-docs/develop/api/Search/#parameters) doc, a query can be made in a free form mode and in a param by param mode.
How can I achieve a search with all the fields passed one by one?
eg. 
?country=France&city=Paris

**Comment by smeijer** [comment]
I think it would require creating a custom provider.

**Comment by giacomotontini** [comment]
I ended up using nominatim api directly...
