### ISSUE TITLE
Map not draggable after search

### ISSUE THREAD

**Issue by rolfboom** [smeijer/leaflet-geosearch#223]
Hi,

I just started using leaflet-geosearch and it looks really great!

One thing I noticed is that the map is not draggable after interacting with the search. Sometimes even before using the search. I thought I might have implemented it wrong, but I have this problem also on your demo at https://smeijer.github.io/leaflet-geosearch/

I reproduced this on your demo page on MacOS 10.14.6 in the latest Chrome, Firefox and Safari.

Here is a screen recording I made on your demo page:
https://www.dropbox.com/s/oq2r1pru1h7zzwe/Screen%20Recording%202020-05-29%20at%2008.29.52.mov?dl=0

Is this a bug, or am I doing something wrong?

**Comment by smeijer** [comment]
You're not doing anything wrong. It's definitely a bug.

**Comment by smeijer** [comment]
fix is on the way

**Comment by smeijer** [comment]
Thanks for the report. The recording was very helpful!

I've just published version `leaflet-geosearch v3.0.6` which includes a fix for this issue. Please let me know if it works for you.

**Comment by rolfboom** [comment]
Yes, v3.0.6 has fixed this issue for me. Thank you very much!
