### ISSUE TITLE
undefined or null markers object on showResult

### ISSUE THREAD

**Issue by abrakadobr** [smeijer/leaflet-geosearch#227]
env: libs are loaded to website with requirejs
error: on clicking any search result error happens and nothing happened - map doesn't change position, no markers appear, no event 'geosearch/showlocation' triggered.
this happens inside showResult method, on line 360, if "this.markers" is null or undefined (i have no idea why it is)
```
   showResult(result, query) {
     ....
[patch.zip](https://github.com/smeijer/leaflet-geosearch/files/4774129/patch.zip)


     const markers = Object.keys(this.markers._layers);
```
but this is small patch, fixing this problem, after everithing works perfect =)

**Comment by abrakadobr** [comment]
[patch.zip](https://github.com/smeijer/leaflet-geosearch/files/4774132/patch.zip)

**Comment by rawhasan** [comment]
I am also getting the same error. Please share if you've found a solution for this.

**Comment by smeijer** [comment]
It would be nice if someone can submit a pull-request with that patch. I can take a look at it later this week.

**Comment by qzminski** [comment]
I had the same problem on 3.0.0 but since I updated to 3.0.5 it seems to be gone.

**Comment by smeijer** [comment]
@rawhasan & @abrakadobr, which version do you use?

**Comment by smrbts** [comment]
I had the same issue, but upgraded from 3.0 to 3.0.6 as @qzminski said, fixed the problem.

**Comment by smeijer** [comment]
Thanks Sam!

I'm going to close this one. Please let me know if the issue persist, so I can reopen it.
