### ISSUE TITLE
How to access the fireEvents in react?

### ISSUE THREAD

**Issue by tbaustin** [smeijer/leaflet-geosearch#231]
![Screen Shot 2020-07-22 at 4 06 24 PM](https://user-images.githubusercontent.com/14001400/88228794-4c150380-cc35-11ea-8eb5-30702ca18467.png)
How to I access this event using `react-leaflet` ?

**Comment by smeijer** [comment]
I haven't tested, but something along the lines of this should work:

```jsx
const setRef = (map) => {
  map.on('geosearch/showlocation', handleResult);
};

<Map ref={setRef} />
```
