### ISSUE TITLE
How to get postal code back from search results?

### ISSUE THREAD

**Issue by tbaustin** [smeijer/leaflet-geosearch#232]
I'm not seeing a postal code/zip code coming back from the search results?

**Comment by smeijer** [comment]
That depends on the provider that you're using. For openstreetmap, you might want to include the `addressdetails` in your response.

Basically, you need to check the additional parameters that your provider supports (in the docs of that provider), and than pass that option to the constructor.

https://smeijer.github.io/leaflet-geosearch/providers/openstreetmap#optional-parameters

```js
const provider = new OpenStreetMapProvider({
  params: {
    'accept-language': 'nl', // render results in Dutch
    countrycodes: 'nl', // limit search results to the Netherlands
    addressdetails: 1, // include additional address detail parts
  },
});
```
