### ISSUE TITLE
zoomLevel not working

### ISSUE THREAD

**Issue by MaRaSu** [smeijer/leaflet-geosearch#233]
Hi,

zoomLevel-option does not seem to work, at least not how I was expecting it to work i.e. set the zoom if no bounds information is available for the selected search result. A quick look at SearchControl.centerMap() looks like it either uses bounds from search result (which e.g. Algolia is not providing for my searches) or a fixed 10 x 10 meter bounds.

retainZoomLevel can be used to prevent this overly tight zooming in, however I would rather not: If map is currently zoomed out to lets say level 11 and does a search for a street name then just doing map center of the street is not good UX. But neither is going all the way to max zoom in either (for my app at least).

**Comment by Dusty211** [comment]
@MaRaSu I ran into the same issue. Suggested fix in pull request: https://github.com/smeijer/leaflet-geosearch/pull/270

**Comment by smeijer** [comment]
Fixed by #270
