### ISSUE TITLE
Error using Algolia provider from CDN

### ISSUE THREAD

**Issue by Emmaqm** [smeijer/leaflet-geosearch#235]
Hi, I'm trying to use geosearch with Algolia as the provider. I can't use imports so I have to pull the library from the cdn.
I'm using the code below, but I'm getting the following error: Cannot read property 'lng' of undefined

`    const provider =  new GeoSearch.AlgoliaProvider({
                params: {
                    hitsPerPage: 5,
                    countries: 'uy',
                }
            });
    let results = provider.search({ query: 'Ombues' });` 

![image](https://user-images.githubusercontent.com/13614499/88471129-89022400-cedb-11ea-8728-0eb06724c79a.png)

**Comment by smeijer** [comment]
Is it a specific query that causes this? It looks like a property on the algolia response that doesn't exist.

Can you replicate this in codepen / jsfiddle?

**Comment by yuriizinets** [comment]
@Emmaqm, seems like that issue was fixed in minor versions somehow. Errors presents in 3.0.0, but 3.0.5 works good.

**Comment by smeijer** [comment]
Thanks @yuriizinets! I'm going to close this issue. Please let me know if the issue still persists.
