### ISSUE TITLE
Need only list of Australia in Search

### ISSUE THREAD

**Issue by dhawal24** [smeijer/leaflet-geosearch#236]
Hi,

Is there any way to get list of any particular country instead of random list..??

As, I want only list of Australia country in search dropdown.

**Comment by smeijer** [comment]
HI @dhawal24 , please check this comment. It includes a code sample that explains how to restrict search results to a certain region.

https://github.com/smeijer/leaflet-geosearch/issues/225#issuecomment-642088856
