### ISSUE TITLE
support laravel 7?

### ISSUE THREAD

**Issue by destiaarti** [smeijer/leaflet-geosearch#237]
can this package support laravel?if i see this , more support react

**Comment by smeijer** [comment]
I don't see why not. It's a leaflet plugin, it doesn't come with react components either.

**Comment by ozilion** [comment]
> 
> 
> I don't see why not. It's a leaflet plugin, it doesn't come with react components either.

But your eaxamples in readme uses React syntax! I am trying your plugin with pure PHP + jQuery but can't use your examples.

**Comment by yuriizinets** [comment]
@ozilion 
Sorry, guy, but I don’t see React syntax here. I’m using this library in Vue.js project. Maybe you’re talking about ES6? Or you can’t rich needed functionality with CDN distribution, without bundler? Please, describe your problem in details. If you are getting any troubles, you can just use providers functionality directly.

**Comment by ozilion** [comment]
Ah sorry my fault yes it's ES6 syntax. Somehow I managed to change search provider to Google and added search input control to map but it can't bring any result. Using OpenStreetMapProvider searching input control being added and can auto search as i write but when I click one of search results it give "Uncaught (in promise) TypeError: can't convert undefined to object" at SearchControl.ts:412:27 I am using CDN links of leaflet v1.7.1 and geosearch v3.0.0

**Comment by yuriizinets** [comment]
Please, try the latest release (3.0.5 at this moment). Some issues may appear for earlier builds only.
If that issue will not be resolved, I'll explore it in details.

**Comment by smeijer** [comment]
I'm going to close this issue. Please feel free to open a new issue, if the `TypeError` also occurs in the latest version.
