### ISSUE TITLE
Getting Latitude and longtitude from given address?

### ISSUE THREAD

**Issue by ozilion** [smeijer/leaflet-geosearch#239]
How can I get Latitude and longtitude from given address? I have a web site written by PHP+jQuery and I need to get lat+long coordinates using given full postal address. For example address can be like this AKSARAY MAH. 1. CAD/SOK. NO:20
ANTAKYA/HATAY/TÜRKİYE

**Comment by smeijer** [comment]
It sounds like you're interested in using the provider alone. Please check the first code sample under usage, in the readme.

https://github.com/smeijer/leaflet-geosearch#usage
