### ISSUE TITLE
style option "bar" will be ignored

### ISSUE THREAD

**Issue by ebastuart** [smeijer/leaflet-geosearch#243]
Hello,
I have upgraded from 2.7.0 to the latest version. After the upgrade my search bar disappeared. Instead of the search bar I just got just a small empty square close to the zoom buttons.  It looks very similar to what I get when I set the style option to "button", but without that somethings happens when I click on it.

![image](https://user-images.githubusercontent.com/5196882/96089253-daacc000-0ec6-11eb-9410-ecf3877f7c19.png)

these settings works for me when I am using 2.7.0. 

```
const searchControl = new GeoSearchControl({
      provider,
      showMarker: false,
      searchLabel: 'Search for an address',
      style: 'bar',
      autoClose: true,
      keepResult: true,
    });

    this._map.addControl(searchControl);
```

Anybody a clue what I am doing wrong or is it a bug?

**Comment by smeijer** [comment]
Seems to be working in the docs. https://smeijer.github.io/leaflet-geosearch/leaflet-control#style

Did you include the correct (new) stylesheet? `https://unpkg.com/leaflet-geosearch/dist/geosearch.css`

**Comment by ebastuart** [comment]
@smeijer Yes you are right, that was the issue. I had an old stylesheet included. Thanks for help!
