### ISSUE TITLE
Limit autocomplete results to a geographic frame

### ISSUE THREAD

**Issue by yurixcode** [smeijer/leaflet-geosearch#246]
Hi! first of all congratulate you for the work done in your bookstore, thank you!

I would like to know if it is possible to limit the results of the geo search to a previously defined geographic frame

For example, if the search limitation is located in Madrid, that the provider returns only results that are included within this geographic area, would it be possible to do this with this library?

I already appreciate your response.

Cheers

**Comment by smeijer** [comment]
Hi, 

Yes, that's possible, but how it exactly works, and to what scope you can limit, depends on the provider that you use.

Please check the provider specific docs, and let me know if you are not able to make it work.

For the OpenStreetMap provider, you can take a look at the example here: https://smeijer.github.io/leaflet-geosearch/providers/openstreetmap#optional-parameters

All providers that we support, have a link on their page to the official docs. And all providers can proxy those official options right to their API. Just like the openstreetmap example shows.

**Comment by cargallo** [comment]
Hi, I'm trying to use optional parameters but it doesn't working. 

Here is the code I'm using const provider = new OpenStreetMapProvider() as de provider:

![image](https://user-images.githubusercontent.com/13320290/98124468-fe45a380-1e91-11eb-9e10-f289c44cac71.png)

and here are the results:

![image](https://user-images.githubusercontent.com/13320290/98124404-ea01a680-1e91-11eb-8a16-b2628d324dda.png)

**Comment by cargallo** [comment]
Ok, I just realize of my error. The provider must be initialized like below, and not at query instance:

```ts
const provider = new OpenStreetMapProvider({
  params: {
    countrycodes: 'ar', // limit search results to Argentina
    addressdetails: 1, // include additional address detail parts
  },
});
```

**Comment by smeijer** [comment]
Correct @cargallo . Thanks for coming back to let us know :slightly_smiling_face:
