### ISSUE TITLE
feature request: close search bar on click on x button 

### ISSUE THREAD

**Issue by LuisReinoso** [smeijer/leaflet-geosearch#254]
Add a config to close search bar on click or emit event when user click on x button in search bar.
![c2aee823-8232-421d-b22c-e4a920d72f6d](https://user-images.githubusercontent.com/7484215/101181977-85b23e00-361b-11eb-90ce-5f28ce9788f6.gif)

It's a llitle bit confuse when search bar is open from search icon.
Suggested source code to edit: https://github.com/smeijer/leaflet-geosearch/blob/develop/src/SearchControl.ts#L193

**Comment by smeijer** [comment]
Fixed by #335
