### ISSUE TITLE
Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by ipaidimarla** [smeijer/leaflet-geosearch#257]
Hi,
Whenever I type a letter in the input box, I am getting this error in my console.
It is failing in autoSearch function. 
I am using OpenStreetMapProviders.  And here is my code snippet
 ```
      const provider = new OpenStreetMapProvider({});
      const search = new GeoSearchControl({
        provider: provider,
        showMarker: true,
        autoClose: true,
        keepResult: true
      });
      map.addControl(search);
```
![image](https://user-images.githubusercontent.com/11392538/101870139-dfdc6300-3b35-11eb-9264-2b21f755e20e.png)

**Comment by smeijer** [comment]
What version of the lib do you use?

**Comment by ipaidimarla** [comment]
Hi, thanks for responding.
I am using 3.0.5

**Comment by ipaidimarla** [comment]
Hi, 
I am not able to figure out why I am getting this error, anyone has any idea?

**Comment by yuriizinets** [comment]
@ipaidimarla
Try to upgrade to the latest version (3.1.0 for now)

**Comment by ipaidimarla** [comment]
@yuriizinets, I tried that but it didn't help.
I figured out that my parent container page is becoming the target of the search form input controller and this is causing the issue. Probably the issue is on my code and I am not sure how to avoid this.

**Comment by smeijer** [comment]
Are you able to share a small reproduction with codesandbox or codepen?

**Comment by ipaidimarla** [comment]
Let me try that?

**Comment by smeijer** [comment]
Closing due to no response from OP.
