### ISSUE TITLE
TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by lucacassani** [smeijer/leaflet-geosearch#258]
Hi, I use leaflet-geosearch^3.2.0 in my VueJs webapp with leaflet and vue2-leaflet modules.
I added to my mapObject GeoSearchControl object with OpenStreetMapProvider (but this issue is present also with AlgoliaProvider). When I type in the search bar a location I get this issue:
`TypeError: Cannot read property 'label' of undefined. `

In fact, as shown below,` t.result` is undefined .. I don't know why I have this issue but I think that `t.label` instead of `t.result.label` could solve it.
Using `resultFormat: ({ result }) => result.label `as option doesn't solve this issue since result is `undefined`. 
Thanks.

![error](https://user-images.githubusercontent.com/9869549/104197833-c3c62d00-5425-11eb-8157-ae4c138e2919.png)

**Comment by lucacassani** [comment]
Downgraded to leaflet-geosearch@3.1.0 and no issues in this version!

**Comment by smeijer** [comment]
Thanks! Are you able to submit a pull request?

**Comment by smeijer** [comment]
This issue has been fixed in `3.2.1`. Please let me know if it's still giving trouble.
