### ISSUE TITLE
Some searchs doesnt work, OSM provider

### ISSUE THREAD

**Issue by sergylopez21** [smeijer/leaflet-geosearch#265]
I have tried to test some random addresses to verify the preciseness. In canada and USA works fine, but in Madrid, Spain there is a issue. I also checked other European countries and these works fine(portugal, france, germany, uk....)

Other cities, such as Barcelona(Spain), doesnt have this issue.

There is my js code:
```
var GeoSearchControl = window.GeoSearch.GeoSearchControl;
var OpenStreetMapProvider = window.GeoSearch.OpenStreetMapProvider;
var provider = new OpenStreetMapProvider();

var searchControl = new GeoSearchControl({
    provider: provider,
    style: 'bar',
});

map.addControl(searchControl);
```

Any random address: **C. de Andrés Mellado, 74, 28015 Madrid**

The address returned:**74, Calle de Andrés Mellado, Gaztambide, Chamberí, Madrid, Área metropolitana de Madrid y Corredor del Henares, Community of Madrid, 28015, Spain**

But the map doesnt center in it nor return raw.result.

**Comment by smeijer** [comment]
I believe this is the same as #264, so closing as duplicate. Please let me know if you think otherwise.
