### ISSUE TITLE
Doesn't work with own type definitions

### ISSUE THREAD

**Issue by tirli** [smeijer/leaflet-geosearch#266]
There is a problem with TypeScript. It seems like 3 days ago [@types/leaflet-geosearch](https://www.npmjs.com/package/@types/leaflet-geosearch) was deprecated. I tried to remove it and use built-in typings, but it doesn't work (`Could not find a declaration file for module 'leaflet-geosearch'` error). 

There is a line `"types": "dist/types.d.ts"` in `package.json`, but there is no `types.d.ts` file, only `index.d.ts`. Changing `package.json` in-place to using the correct path helps.

I wanted to create the PR, but it seems like it is a build/publishing setting, and I cannot find that line or something related to it in the repo.

**Comment by smeijer** [comment]
Thanks! I think this line in package.json should get updated. 

https://github.com/smeijer/leaflet-geosearch/blob/11e4e27f804dfc6566d7ae02f6c61ef4b4f20a7c/package.json#L13

**Comment by tirli** [comment]
Oh, I was on `master` branch, not `develop`. I'll create the PR soon
