### ISSUE TITLE
Search Control  has no default export

### ISSUE THREAD

**Issue by taopen4** [smeijer/leaflet-geosearch#271]
Hi,
I did play in angular 11 with error:

```
Error: node_modules/leaflet-geosearch/dist/SearchControl.d.ts:1:8 - error TS1192: Module '"C:/Users/Admin/WebstormProjects/map/node_modules/@types/leaflet/index"' has no default export.

1 import L, { ControlPosition, FeatureGroup, MarkerOptions, Map } from 'leaflet';
```

Please help me! Thank you so much!

**Comment by smeijer** [comment]
We don't have any specific angular bindings / code. But also indeed don't have an default export. 

Please see this section in the readme to see how you should import:

https://github.com/smeijer/leaflet-geosearch#using-with-leafletjs

**Comment by VjeraTurk** [comment]
@taopen4 Did you manage to solve this? 
[This solution](https://www.gitmemory.com/issue/smeijer/leaflet-geosearch/272/826279258) solves it, but I need a different one.
