### ISSUE TITLE
import failed: Angular11, leaflet1.7.1;  "error TS1192: Module '.../leaflet/index" has no default export"

### ISSUE THREAD

**Issue by gianmarco-todesco** [smeijer/leaflet-geosearch#272]
I'm trying to use leaflet-geosearch in an Angular11 webapp. I'm using leaflet 1.7.1. 
The import of SearchControl.d.ts fails with an error message.
Quick fix (SearchControl.d.ts:1):

Replace line:
> import L, { ControlPosition, FeatureGroup, MarkerOptions, Map } from 'leaflet';

With lines:
> import * as L from 'leaflet';
> import { ControlPosition, FeatureGroup, MarkerOptions, Map } from 'leaflet';

**Comment by pedropapa** [comment]
Try adding `"allowSyntheticDefaultImports": true,` to your `tsconfig.json`.

**Comment by gianmarco-todesco** [comment]
It works. Thank you.
gm

**Comment by smeijer** [comment]
Thanks for the help @pedropapa!

**Comment by gianmarco-todesco** [comment]
you are welcome
gm

**Comment by VjeraTurk** [comment]
In my case, the same flag had to be set in `tsconfig.app.json`, not `tsconfig.json`
