### ISSUE TITLE
Some Canada Zip codes aren't working

### ISSUE THREAD

**Issue by tbaustin** [smeijer/leaflet-geosearch#273]
This is for the OSM provider and passing in `ca, us` into country codes.

Hopefully can make this straight to the point. There are multiple, but just an example of one zip code that isn't working is `T6X 1C3`, but if I only do the first 3 it seems to work. 

https://nominatim.openstreetmap.org/search?countrycodes=ca%20us&addressdetails=1&format=json&q=T6X

When adding the full zip it doesn't work for some reason:

https://nominatim.openstreetmap.org/search?countrycodes=ca%20us&addressdetails=1&format=json&q=T6X%201C3

Not sure if this is expected or not? There are some other zip codes that also don't work.

**Comment by smeijer** [comment]
I'm closing this issue because you're asking a question that's not within the scope of this project. I don't maintain the nominatim servers, so I can't fix it, nor can I say anything meaningful about the expected workings without further research.
