### ISSUE TITLE
dist/bundle.js is no longer published

### ISSUE THREAD

**Issue by dearmasmichael** [smeijer/leaflet-geosearch#274]
Hi, I found an example of how to use this plugin with OpenStreetMap  (Nominating) from Javascript, but it is using an older version and when I try a newer version I get an error as if it didn't support the OpenStreetMap Provider anymore:

**Uncaught TypeError: Cannot read property 'OpenStreetMapProvider' of undefined**

I get that error when I try this:
`const provider = new window.GeoSearch.OpenStreetMapProvider();`

using this:
`<script type="text/javascript" src="https://unpkg.com/leaflet-geosearch@latest/dist/bundle.min.js"></script>`

The latest version I found that still supported it was 3.2.0.
That is, I have to use this:
`<script type="text/javascript" src="https://unpkg.com/leaflet-geosearch@3.2.0/dist/bundle.min.js"></script>`

Are you dropping support for the only one Provider that is free?
Please, advise.
Thanks,
Michael

**Comment by smeijer** [comment]
Thanks for taking the time to report this.

OpenStreetMapProvider is still part of this project. But I see that `3.2.1` was the last version publishing the bundle. I'll try to fix that later today.

https://unpkg.com/browse/leaflet-geosearch@3.2.2/dist/

**Comment by smeijer** [comment]
Should be fixed in `3.3.2`.

**Comment by dearmasmichael** [comment]
I'm glad to hear that.
Thanks!
