### ISSUE TITLE
Not load Destination after click search result

### ISSUE THREAD

**Issue by Mansoun** [smeijer/leaflet-geosearch#275]
Hi. 
I have a question and an issue due use this library.
first, every i tried the box shown top of the map , i failed and every time this appears beside the map as bar.
second, when i choose one of address shows by search input, the map going to freez and only zoom bottum works unti refresh page!
there is an error : Uncaught (in promise) TypeError: Cannot convert undefined or null to object
on line 423:  e = Object.keys(this.markers.t);

please help me. thanks sir.

**Comment by Dak0r** [comment]
I can confirm that I also get this error when selecting a search result:

`Uncaught (in promise) TypeError: can't convert undefined to object
    showResult SearchControl.ts:412
    onSubmit SearchControl.ts:404
    promise callback*onSubmit SearchControl.ts:401
    handleClick SearchControl.ts:218
    onClick resultList.ts:92
    t resultList.ts:27
    initialize SearchControl.ts:215
    i Class.js:22
    s geosearch.umd.js:1
    R SearchControl.ts:503
    <anonymous> trailsmap.js:46`

**Comment by smeijer** [comment]
Closing, as this should be fixed in the latest version.

**Comment by kennankole** [comment]
Thanks!! @smeijer 
It fixed it for me.
