### ISSUE TITLE
Can't make more than 1 search

### ISSUE THREAD

**Issue by SolimanGit** [smeijer/leaflet-geosearch#291]
Hi !
I have a weird error : `TypeError: Cannot create property '_leaflet_id' on string '182'`.
It works perfectly for the 1st search but when I'm trying to search an second address, in the bar it's perfect, but when I press enter it doesn't do anything.
I'm using a vue component to use the geosearch and this might be the problem but I can't see why.
Thank you in advance.

vue_geosearch from fega -> [LINK](https://github.com/fega/vue2-leaflet-geosearch)
```<template>
  <div></div>
</template>

<script>
// import L from 'leaflet';
import { GeoSearchControl } from 'leaflet-geosearch';
export default {
  props: {
    options: {
      required: true
    }
  },
  name: 'v-geosearch',
  mounted() {
    this.add();
  },
  beforeDestroy() {
    this.remove();
  },
  methods: {
    deferredMountedTo(parent) {
      const searchControl = new GeoSearchControl(this.options);
      parent.addControl(searchControl);
      searchControl.getContainer().onclick = e => {
        e.stopPropagation();
      };
    },
    remove() {
      if (this.markerCluster) {
        this.$parent.removeLayer(this.markerCluster);
      }
    },
    add() {
      if (this.$parent._isMounted) {
        this.deferredMountedTo(this.$parent.mapObject);
      }
    }
  }
};```

**Comment by smeijer** [comment]
I don't support the vue plugin, but I do see that they use an old version of this library (3.1.0 while we are on 3.5.0). An upgrade might help.
