### ISSUE TITLE
unusual bounds checks in provider tests

### ISSUE THREAD

**Issue by missinglink** [smeijer/leaflet-geosearch#297]
Hi Stephan,

I was writing a new provider today and noticed some code which stumped me, it looks like this, and is present in several provider tests:

```js
expect(result.bounds[0][0]).toBeGreaterThan(result.bounds[0][1]);
expect(result.bounds[1][0]).toBeGreaterThan(result.bounds[1][1]);
expect(result.bounds[0][0]).toBeLessThan(result.bounds[1][0]); // south less than north
expect(result.bounds[0][1]).toBeLessThan(result.bounds[1][1]); // west less than east
```

the bottom two tests are valid, they compare min/max values of the same dimension to ensure the order is valid.

the issue is with the top two, where they are checking that one dimension is greater than the other, this only makes sense in some part of the world and probably shouldn't be in the unit tests, I got confused when I copied the logic and it failed.

let me know what you think and I can clean it up?

**Comment by smeijer** [comment]
Yeah, that makes sense. Never thought of it to be honest 😅 (living at 53, 5)

Doesn't the same account for the other coordinates? The world is a sphere, so if you would stand on the north pole, the same applies to all 4 checks, right?

**Comment by missinglink** [comment]
agh, so actually this is a bug is inherited from the [source data](https://github.com/whosonfirst-data/whosonfirst-data-admin-fj/blob/master/data/856/327/55/85632755.geojson), I'll file an issue with WOF.

**Comment by smeijer** [comment]
Thanks for the explanation. I had no idea, but it makes sense now. Please feel free to submit the fix that you feel is best. 

I've also added you as a collaborator on the project, so you can now make your branches directly on the repo rather than your fork if you want.
