### ISSUE TITLE
error occured while using the package...showing api error ..

### ISSUE THREAD

**Issue by sweety-124** [smeijer/leaflet-geosearch#309]

**Comment by darrenklein** [comment]
@sweety-124 In order for the maintainer of this repo and other devs to help resolve any potential issue, you'll need to provide more information about the problem you encountered. Some helpful things would be -

- What was the user doing when the error occurred? You mention an API error - what does the error say? What URL is it pointing at?
- Was there any error text logged to the JS console, or any error responses in the network tab?
- Which version of this NPM package are you using?
- Which provider are you using?

You might also consider providing some of your code.

**Comment by sweety-124** [comment]
shows

![err](https://user-images.githubusercontent.com/59157591/148388189-6a494a39-4515-4771-b73d-0edff269d983.png)

**Comment by sweety-124** [comment]
> @sweety-124 In order for the maintainer of this repo and other devs to help resolve any potential issue, you'll need to provide more information about the problem you encountered. Some helpful things would be -
> 
> * What was the user doing when the error occurred? You mention an API error - what does the error say? What URL is it pointing at?
> * Was there any error text logged to the JS console, or any error responses in the network tab?
> * Which version of this NPM package are you using?
> * Which provider are you using?
> 
> You might also consider providing some of your code.

please check
