### ISSUE TITLE
Add custom marker and eventhandler

### ISSUE THREAD

**Issue by spotnick** [smeijer/leaflet-geosearch#310]
Hi all!

First, thanks for your great implementation. It just works and also in a very beautiful way!

I have to need to provide a custom popup. I dont want to use the integrated popup and use a modal or a drawer on the side instead. With react-leaflet I´m able to create an onClick eventhandler on the marker and open a modal on click on of the marker like this:

```javascript
<MapContainer
    center={[0, 0]}
    zoom={14}
    scrollWheelZoom={true}
    dragging={true}
    zoomControl={true}
    style={{ height: '100%', width: '100%' }}>
        <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            />
            <Marker
                position={[0, 0]}
                draggable={true}
                eventHandlers={{ click: handleOnClick }}>
                <Modal open={open} setOpen={handleOnClick} />
            </Marker>
        <LeafletSearch />    
</MapContainer>
```

Is this somehow possible with the implementation or rather not? In the documentation I found this:

```javascript
map.on('geosearch/showlocation', yourEventHandler);
```

this could be somehow what I´m looking for but I dont know how to use it with react-leaflet :(. Maybe somebody could give me a poke into the right direction?

Thanks a lot folks!

**Comment by iamtekson** [comment]
Perfect! Thank you very much for adding the solution. Really appreciated!
