### ISSUE TITLE
Combining geosearch with What3Words search

### ISSUE THREAD

**Issue by Vollando** [smeijer/leaflet-geosearch#348]
Hi I'm trying to have the leaflet geosearch work while also providing the what3words autosuggest functionality. An example of the intended design can be found on their website https://what3words.com/pretty.needed.chill

![image](https://user-images.githubusercontent.com/14557023/194059130-967a4ea8-194c-48dc-b617-23d05d782037.png)

Looking at their [documentation](https://developer.what3words.com/tutorial/combining-the-what3words-js-autosuggest-component-with-a-leafletjs-map#usage) the normal way of doing this would be to wrap a input element in the HTML file in the AutoSuggest component. Because the GeoSearchControl is created programmatically I can't see a way to do this.

**Comment by smeijer** [comment]
I recommend creating a custom provider.
