### ISSUE TITLE
The search style is messed up. How can I fix this issue?

### ISSUE THREAD

**Issue by ali-mozaffari** [smeijer/leaflet-geosearch#357]
![Capture](https://user-images.githubusercontent.com/103691384/215332223-6d0a70ab-4ea0-4d74-97d9-08343f79d5db.PNG)

Is there any way to manipulate the CSS style?

![Capture2](https://user-images.githubusercontent.com/103691384/215332387-e442af72-689f-4ff5-8e10-2ed88b545c24.PNG)

I need to customize it like this.

**Comment by Anyman552** [comment]
Did you import the CSS file according to the installation? https://smeijer.github.io/leaflet-geosearch/
 
`import 'node_modules/leaflet-geosearch/dist/geosearch.css';`
