### ISSUE TITLE
Error when importing leaflet-geosearch using Vite/Typescript 5

### ISSUE THREAD

**Issue by neilenns** [smeijer/leaflet-geosearch#370]
I'm attempting to use leaflet-geosearch in a React Typescript project created with Vite's react-ts template. I've done `npm install leaflet-geosearch` and imported it this way:

```typescript
import "leaflet-geosearch/dist/geosearch.css";
import { GeoSearchControl, OpenStreetMapProvider } from "leaflet-geosearch";
```

Unfortunately typescript throws this error:

```
Could not find a declaration file for module 'leaflet-geosearch'. 'd:/git/test/test-app/node_modules/leaflet-geosearch/dist/geosearch.module.js' implicitly has an 'any' type.
  There are types at 'd:/git/test/test-app/node_modules/leaflet-geosearch/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'leaflet-geosearch' library may need to update its package.json or typings.
```

I've messed around with this for a while but can't get it to go away. I have no issues with the import or the types in a different React Typescript project that was created using create-react-app and Typescript version 4.

**Comment by GdevDdev** [comment]
I have exactly the same problem, I also hope to get a solution.

**Comment by ridhosatriawan** [comment]
same problem here 😢
