### ISSUE TITLE
TypeError: t3.trim is not a function coords.ts 

### ISSUE THREAD

**Issue by mugu-fatman** [smeijer/leaflet-geosearch#379]
Hi , Thanks for the wonderful library , 
I am trying to use leaflet-geosearch in my svelte-kit application. but getting an this type error 

```
coords.ts:4 Uncaught (in promise) TypeError: t3.trim is not a function
    at g (coords.ts:4:19)
    at NewClass.onSubmit (SearchControl.ts:396:20)
    at t3.handleClick (SearchControl.ts:224:16)
    at HTMLDivElement.onClick (resultList.ts:113:10)
```
    
 I am using the searchControl as below 

```
		const searchControl  = new GeoSearchControl({
			style: 'bar',
			provider: new OpenStreetMapProvider(),
			showMarker: true
		});

		map.addControl(searchControl);

```

using typescript version 

`"typescript": "^5.0.0",`

**Comment by mr339** [comment]
what was this closed? im also facing the same issue.

**Comment by gjvoosten** [comment]
Same here:
![Screenshot from 2023-10-11 13-25-57](https://github.com/smeijer/leaflet-geosearch/assets/445238/9aa68865-1f52-46c6-84d8-37d124fcdbde)

Downgrading to the previous version makes the error disappear. Please reopen or provide a reason why this was closed.

**Comment by mtmail** [comment]
mugu-fatman closed it himself. It wasn't the library maintainer.

**Comment by gjvoosten** [comment]
I've opened a new issue: #382

**Comment by mugu-fatman** [comment]
Thank you, There was already another issue opened for the same reason
