### ISSUE TITLE
geosearch returns incorrect bounds sometimes

### ISSUE THREAD

**Issue by koskinpark** [smeijer/leaflet-geosearch#391]
Open https://smeijer.github.io/leaflet-geosearch/providers/openstreetmap
Type "France" in the search bar -> select France in autocomplete 

This is what you will see:

<img width="1281" alt="Снимок экрана 2024-01-26 в 18 00 30" src="https://github.com/smeijer/leaflet-geosearch/assets/6603030/6856ed5a-b3ad-4db1-8d3d-30847c80e7cf">

**Comment by mtmail** [comment]
I don't think the java library can do anything about that. You'd need an issue with the underlying API which returns the data.

France has territories around the world. https://en.wikipedia.org/wiki/Overseas_France It's still unexpected, but geographically correct. What most people expect is Metropolitan France https://www.openstreetmap.org/relation/1403916
