### ISSUE TITLE
draggable, update longlat after dragging the marker

### ISSUE THREAD

**Issue by vlasvlasvlas** [smeijer/leaflet-geosearch#71]
Hi, i needed to get the new longlat after i dragged the marker, i already set draggable true at geosearch.js

this is my js

```
      new L.Control.GeoSearch({
              provider: new L.GeoSearch.Provider.Esri()
          }).addTo(m);


        m.on('geosearch_showlocation', (result) => {

        markerLng = result.Location.X;

        markerLat = result.Location.Y;

        });
```

i understand i must get the dragend something like: 

```
marker.on('dragend', function(event) {
    var marker = event.target;  
    var result = marker.getLatLng(); 
    console.log(result);
});
```

but i cant find how the name of the created marker

txs!

**Comment by interactivevalues** [comment]
hi, did you find a solution?
I have the same problem right now!

cheers,
ToM

**Comment by smeijer** [comment]
Thanks to @Ville6000, this should now be possible by listening to the `geosearch/marker/dragend` event.

**Comment by mfreeman451** [comment]
How do I do this in the Vue component?

**Comment by mfreeman451** [comment]
this.$refs.myMap.mapObject.on('geosearch/marker/dragend', this.handleMarkerDrag)
