### ISSUE TITLE
Feature: Possible to clear a search and search marker.

### ISSUE THREAD

**Issue by newmanw** [smeijer/leaflet-geosearch#74]
Awesome library, thanks so much.

Wondering if you have considered a way to 'clear' a search.  Currently when you search and a location is found a marker is added to the map.  The search form is cleared but the marker remains, leaving no way to clear the maker.  Thoughts on an option to leave search results in the box with a clear icon or 'x' in the form that would clear the current search text and the marker from the map?

**Comment by tstibbs** [comment]
Note until this feature is implemented, you may find https://github.com/smeijer/L.GeoSearch/pull/86 useful as it adds a link to the popup that allows you to remove the marker.

**Comment by smeijer** [comment]
Closed by #123 

![clear-result](https://cloud.githubusercontent.com/assets/1196524/26371421/f939bbb6-3ffa-11e7-9624-fbe8b2226f46.gif)
