### ISSUE TITLE
Moving GeoSearch with Provider outside the map?

### ISSUE THREAD

**Issue by penproductions** [smeijer/leaflet-geosearch#75]
I'm using https://github.com/smeijer/L.GeoSearch as my search and I'm running into a problem. They have an example of how to move the search out side of the Map but it doesn't use the provider.
At the top you can see the code that is commented out that works with OpenStreetMap but I can't get that into the div that I want. Below it is the code that I can move to where I want but will not search correctly. 

How is this done?

`initSearch:function(){
        // Adds search to the map and works as it should  
            // but doesn't add it to the correct div.
        // new L.Control.GeoSearch({
        //     provider: new L.GeoSearch.Provider.OpenStreetMap()
        // }).addTo(this.map);

```
    // Adds search box to the correct div but doesn't provide GeoSearch.
    var markersLayer = new L.LayerGroup();
    this.map.addLayer(markersLayer);

    this.map.addControl( new L.Control.Search({
        container: 'newPRLocationContainer',
        layer: markersLayer,
        initial: false,
        collapsed: false
    }) );

},`
```

**Comment by penproductions** [comment]
What I have done to sort this out is just add it to the map then pull it back out and add it to the correct parent. Is this the best way?

**Comment by smeijer** [comment]
The control has been rewritten, whereby this principle has been kept in mind. The base functionality now lives outside of leaflet, where by the control is being put in the map when required, instead of the other way around.

Long story short:
```js
// import
import { OpenStreetMapProvider } from 'leaflet-geosearch';

// setup
const provider = new OpenStreetMapProvider();

// search
const results = await provider.search({ query: input.value });
```

Also see: https://github.com/smeijer/leaflet-geosearch#usage
