### ISSUE TITLE
Can i use this function on Leaflet directive for AngularJS?

### ISSUE THREAD

**Issue by GustavSvensson** [smeijer/leaflet-geosearch#76]
This function works perfect for leaflet, is it possible to use this in Leaflet directive for AngularJS (http://tombatossals.github.io/angular-leaflet-directive/#!/) ?

**Comment by smeijer** [comment]
I don't have any experience with Angular directives. Did you discover how this can be done, or what needs to be done to make this possible?

Would be awesome if we can explain this in the docs.

**Comment by smeijer** [comment]
Closing for now. In case someone has any information; please let me know, so we can update the docs and provide examples.
