### ISSUE TITLE
position: 'topcenter' from the example doesn't work

### ISSUE THREAD

**Issue by needlestack** [smeijer/leaflet-geosearch#78]
It seems that in the current version when calling `new L.Control.GeoSearch` the argument `position: 'topcenter'` doesn't seem to work (javascript error). This is unfortunate because I think the topcenter position (which I saw working in an earlier version) was the nicest positioning option.

**Comment by chinaowl** [comment]
I would also like to be able to use the `topcenter` position. Also, is there an option that makes the search bar always visible, instead of on hover?

**Comment by hanginwithdaddo** [comment]
Any update on this issue?

**Comment by smeijer** [comment]
The `topcenter` is indeed an old option. I think the old style should come back and make the option configurable. 

This plugin needs some refactoring. But at the moment I'm a little short in time.

**Comment by hanginwithdaddo** [comment]
Thanks for the update. I guess I liked the way it visually showed before, but I'm seeing more and more examples with other apps/web sites where you need to click something like a search button to have the search area appear. It's just new/different.  The one potential issue is that we tend to put several buttons on the left-hand side, to match leaflet's default positioning, but we can end up running out of space on small screens. Thanks again for your quick reply!!

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```
