### ISSUE TITLE
Include full results from Google GeoSearch?

### ISSUE THREAD

**Issue by skinnyjames** [smeijer/leaflet-geosearch#82]
Would it be problematic to include the provider's full result object into GeoSearch.Result?
I think it would be nice to be able to access googles address components.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```

I still must write some doc's. But on each result, the full unprocessed object is available under `raw`.
