### ISSUE TITLE
Google geocoder not working. Invalid key map error

### ISSUE THREAD

**Issue by ShenbagaRajanV** [smeijer/leaflet-geosearch#84]
I'm using google geocoder and getting invalid key map error. I referred your demo and developed an application. But gives me Invalid key map error. Should I somewhere mention the googlemaps api key? How can I solve this?

**Comment by amoswachanga** [comment]
@ShenbagaRajanV I had the same challenge sometime back, but after checking out the source code, I got it working, probably it needs to be documented somewhere; but here's the solution:

1. Go to the following script : [l.geosearch.provider.google.js](https://github.com/smeijer/L.GeoSearch/blob/develop/src/js/l.geosearch.provider.google.js)
2. Look for the line: 
`var key = (typeof(this.options.key) !== 'undefined')? this.options.key : "YOUR_API_KEY";`
3. Replace "YOUR_API_KEY" [with your generated Google Maps API key](https://code.google.com/apis/console)

**Comment by smeijer** [comment]
Is this not working for you?

```js
new L.Control.GeoSearch({
    provider: new L.GeoSearch.Provider.Google({
        key: 'YOUR_KEY_HERE'
    })
}).addTo(map);
```

**Comment by ShenbagaRajanV** [comment]
Thanks it worked! But now when I use the callback function as,

 var googleGeocodeProvider = new L.GeoSearch.Provider.Google(),
  addressText = 'Amsterdam';

googleGeocodeProvider.GetLocations( addressText, function ( data ) {
  alert("geocoded")
});

The callback function is not working. Alert function doesnt work. Should I need to change anything? Pls help on this!

**Comment by aabraamyan** [comment]
@smeijer That doesn't work. 

It does however work if you hardcode the API key into the js file as @amoswachanga suggested.

**Comment by irmela** [comment]
I'm having the same problem. Even when I hardcode the API key as @amoswachanga suggested, it doesn't work.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```
