### ISSUE TITLE
keypress event not always recognized

### ISSUE THREAD

**Issue by arminus** [smeijer/leaflet-geosearch#85]
I observed that this control's keypress event handler is not reliably triggered in my application (maybe some side effects with other event handlers). At any rate, adding the if (e.keyCode === enterKey) block also to the _onKeyUp handler seems to work much better for me.

Any reason to not hook it into that as well?

**Comment by smeijer** [comment]
I can not reproduce this behavior. Are you willing to test the `next` release that I'm currently finishing up?

Install with:
```sh
npm install leaflet-geosearch@next --save
```
