### ISSUE TITLE
Submit a new release?

### ISSUE THREAD

**Issue by MFrancesco** [smeijer/leaflet-geosearch#88]
Due to the problem reported in #77 , the library, when downloaded through bower is not working correctly if using the google provider.
Since most of the user is going to use such provider, i think that a new release containing that fix would be welcome.

**Comment by smeijer** [comment]
Valid point; I hope I can finish a release at the end of this month. Sorry for the huge delays.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```
