### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by wuk986** [smeijer/leaflet-geosearch#98]
i want to implent leaflet-geosearch to my leaflet map.
i used yarn to get the latest files and added the `bundle.min.js` and `stlye.css` to my index.html

i also added 
1:`import L from 'leaflet';`
2:`import { GeoSearchControl, OpenStreetMapProvider } from 'leaflet-geosearch';`
3:`const provider = new OpenStreetMapProvider();`
4:`const searchControl = new GeoSearchControl({`
5:`provider: provider,`
6:`});`
7:`const map = new L.Map('map');`
8:`map.addControl(searchControl);`

to my `map.js` (same directory as `leaflet.js`)

when i open the index.html i get the following error: 
>Uncaught SyntaxError: Unexpected token import   at map.js:1

the directory tree is like:

map
|--leaflet
|    |--map.js
|
|--leaflet-geosearch
|
index.html

have anyone an advice for me?

thanks!

**Comment by smeijer** [comment]
If you're using `yarn` or `npm` to install and bundle dependencies, than you don't need to add the `bundle.min.js` file.

The `import` statements do require to be recompiled to es5 due to browser support, by something like `babel`.

Please see #92 on how to use without using es6 coding style.
